function [Jp1,Jp2,Jpw] = hand_symbolic_jacobians(x, y, z, yaw, pit, rol, q1, q2, l1, l2, l3, l4)
% Hand Jacobians Computation (created using test_jacobian in test

Jp1 = [  1, 0, 0, l1*(cos(rol)*cos(yaw) - sin(pit)*sin(rol)*sin(yaw)) + l3*(cos(q2)*(cos(q1)*(cos(rol)*cos(yaw) - sin(pit)*sin(rol)*sin(yaw)) - sin(q1)*(cos(yaw)*sin(rol) + cos(rol)*sin(pit)*sin(yaw))) - sin(q2)*(cos(q1)*(cos(yaw)*sin(rol) + cos(rol)*sin(pit)*sin(yaw)) + sin(q1)*(cos(rol)*cos(yaw) - sin(pit)*sin(rol)*sin(yaw)))) + l2*(cos(q1)*(cos(rol)*cos(yaw) - sin(pit)*sin(rol)*sin(yaw)) - sin(q1)*(cos(yaw)*sin(rol) + cos(rol)*sin(pit)*sin(yaw))),  cos(pit)*cos(yaw)*(l2*sin(q1 + rol) + l1*sin(rol) + l3*sin(q1 + q2 + rol)), - l1*(sin(rol)*sin(yaw) - cos(rol)*cos(yaw)*sin(pit)) - l3*(cos(q2)*(cos(q1)*(sin(rol)*sin(yaw) - cos(rol)*cos(yaw)*sin(pit)) + sin(q1)*(cos(rol)*sin(yaw) + cos(yaw)*sin(pit)*sin(rol))) + sin(q2)*(cos(q1)*(cos(rol)*sin(yaw) + cos(yaw)*sin(pit)*sin(rol)) - sin(q1)*(sin(rol)*sin(yaw) - cos(rol)*cos(yaw)*sin(pit)))) - l2*(cos(q1)*(sin(rol)*sin(yaw) - cos(rol)*cos(yaw)*sin(pit)) + sin(q1)*(cos(rol)*sin(yaw) + cos(yaw)*sin(pit)*sin(rol))), - l3*(cos(q2)*(cos(q1)*(sin(rol)*sin(yaw) - cos(rol)*cos(yaw)*sin(pit)) + sin(q1)*(cos(rol)*sin(yaw) + cos(yaw)*sin(pit)*sin(rol))) + sin(q2)*(cos(q1)*(cos(rol)*sin(yaw) + cos(yaw)*sin(pit)*sin(rol)) - sin(q1)*(sin(rol)*sin(yaw) - cos(rol)*cos(yaw)*sin(pit)))) - l2*(cos(q1)*(sin(rol)*sin(yaw) - cos(rol)*cos(yaw)*sin(pit)) + sin(q1)*(cos(rol)*sin(yaw) + cos(yaw)*sin(pit)*sin(rol))), -l3*(cos(q2)*(cos(q1)*(sin(rol)*sin(yaw) - cos(rol)*cos(yaw)*sin(pit)) + sin(q1)*(cos(rol)*sin(yaw) + cos(yaw)*sin(pit)*sin(rol))) + sin(q2)*(cos(q1)*(cos(rol)*sin(yaw) + cos(yaw)*sin(pit)*sin(rol)) - sin(q1)*(sin(rol)*sin(yaw) - cos(rol)*cos(yaw)*sin(pit))));
        0, 1, 0, - l1*(cos(rol)*sin(yaw) + cos(yaw)*sin(pit)*sin(rol)) - l3*(cos(q2)*(cos(q1)*(cos(rol)*sin(yaw) + cos(yaw)*sin(pit)*sin(rol)) - sin(q1)*(sin(rol)*sin(yaw) - cos(rol)*cos(yaw)*sin(pit))) - sin(q2)*(cos(q1)*(sin(rol)*sin(yaw) - cos(rol)*cos(yaw)*sin(pit)) + sin(q1)*(cos(rol)*sin(yaw) + cos(yaw)*sin(pit)*sin(rol)))) - l2*(cos(q1)*(cos(rol)*sin(yaw) + cos(yaw)*sin(pit)*sin(rol)) - sin(q1)*(sin(rol)*sin(yaw) - cos(rol)*cos(yaw)*sin(pit))), -cos(pit)*sin(yaw)*(l2*sin(q1 + rol) + l1*sin(rol) + l3*sin(q1 + q2 + rol)), - l1*(cos(yaw)*sin(rol) + cos(rol)*sin(pit)*sin(yaw)) - l3*(cos(q2)*(cos(q1)*(cos(yaw)*sin(rol) + cos(rol)*sin(pit)*sin(yaw)) + sin(q1)*(cos(rol)*cos(yaw) - sin(pit)*sin(rol)*sin(yaw))) + sin(q2)*(cos(q1)*(cos(rol)*cos(yaw) - sin(pit)*sin(rol)*sin(yaw)) - sin(q1)*(cos(yaw)*sin(rol) + cos(rol)*sin(pit)*sin(yaw)))) - l2*(cos(q1)*(cos(yaw)*sin(rol) + cos(rol)*sin(pit)*sin(yaw)) + sin(q1)*(cos(rol)*cos(yaw) - sin(pit)*sin(rol)*sin(yaw))), - l3*(cos(q2)*(cos(q1)*(cos(yaw)*sin(rol) + cos(rol)*sin(pit)*sin(yaw)) + sin(q1)*(cos(rol)*cos(yaw) - sin(pit)*sin(rol)*sin(yaw))) + sin(q2)*(cos(q1)*(cos(rol)*cos(yaw) - sin(pit)*sin(rol)*sin(yaw)) - sin(q1)*(cos(yaw)*sin(rol) + cos(rol)*sin(pit)*sin(yaw)))) - l2*(cos(q1)*(cos(yaw)*sin(rol) + cos(rol)*sin(pit)*sin(yaw)) + sin(q1)*(cos(rol)*cos(yaw) - sin(pit)*sin(rol)*sin(yaw))), -l3*(cos(q2)*(cos(q1)*(cos(yaw)*sin(rol) + cos(rol)*sin(pit)*sin(yaw)) + sin(q1)*(cos(rol)*cos(yaw) - sin(pit)*sin(rol)*sin(yaw))) + sin(q2)*(cos(q1)*(cos(rol)*cos(yaw) - sin(pit)*sin(rol)*sin(yaw)) - sin(q1)*(cos(yaw)*sin(rol) + cos(rol)*sin(pit)*sin(yaw))));
        0, 0, 1,                                                                                                                                                                                                                                                                                                                                                                                                                                                     0,           sin(pit)*(l2*sin(q1 + rol) + l1*sin(rol) + l3*sin(q1 + q2 + rol)),                                                                                                                                                                                                                                                                                                                                                                                    -cos(pit)*(l2*cos(q1 + rol) + l1*cos(rol) + l3*cos(q1 + q2 + rol)),                                                                                                                                                                                                                                                                                                                                            -cos(pit)*(l2*cos(q1 + rol) + l3*cos(q1 + q2 + rol)),                                                                                                                                                                                                       -(l3*(cos(pit + q1 + q2 + rol) + cos(q1 - pit + q2 + rol)))/2];
    
Jp2 = [  1, 0, 0, l4*(cos(yaw)*sin(rol) + cos(rol)*sin(pit)*sin(yaw)), -l4*cos(pit)*cos(rol)*cos(yaw), l4*(cos(rol)*sin(yaw) + cos(yaw)*sin(pit)*sin(rol)), 0, 0;
        0, 1, 0, l4*cos(rol)*cos(yaw)*sin(pit) - l4*sin(rol)*sin(yaw),  l4*cos(pit)*cos(rol)*sin(yaw), l4*(cos(rol)*cos(yaw) - sin(pit)*sin(rol)*sin(yaw)), 0, 0;
        0, 0, 1, 0, -l4*cos(rol)*sin(pit), -l4*cos(pit)*sin(rol), 0, 0];
 
Jpw = [  1, 0, 0, 0, 0, 0, 0, 0;
        0, 1, 0, 0, 0, 0, 0, 0;
        0, 0, 1, 0, 0, 0, 0, 0];
    
end

